pub struct Job {
    pub input: &'static str,
    pub output: &'static str,
    pub preset: &'static str,
    pub stage: &'static str,
    pub duration: &'static str,
    pub input_size_mb: u64,
    pub target_output_mb: u64,
    pub target_bitrate_kbps: u64,
    pub video_codec: &'static str,
    pub audio_codec: &'static str,
    pub resolution: &'static str,
    pub fps: &'static str,
    pub failure_reason: Option<&'static str>,
}

pub fn demo_jobs() -> Vec<Job> {
    vec![
        Job {
            input: "lesson_01.mov",
            output: "lesson_01.mp4",
            preset: "h264 social mp4",
            stage: "video encode",
            duration: "00:03:24",
            input_size_mb: 842,
            target_output_mb: 317,
            target_bitrate_kbps: 1240,
            video_codec: "h264 -> h264",
            audio_codec: "aac stereo",
            resolution: "1920x1080",
            fps: "23.98",
            failure_reason: None,
        },
        Job {
            input: "intro_master.mov",
            output: "intro_master.webm",
            preset: "webm preview",
            stage: "audio mux",
            duration: "00:00:42",
            input_size_mb: 128,
            target_output_mb: 44,
            target_bitrate_kbps: 980,
            video_codec: "prores -> vp9",
            audio_codec: "opus stereo",
            resolution: "1280x720",
            fps: "25.00",
            failure_reason: None,
        },
        Job {
            input: "teaser_cut.mov",
            output: "teaser_cut.mp4",
            preset: "h264 small mp4",
            stage: "finalizing",
            duration: "00:01:18",
            input_size_mb: 264,
            target_output_mb: 96,
            target_bitrate_kbps: 1100,
            video_codec: "h264 -> h264",
            audio_codec: "aac stereo",
            resolution: "1920x1080",
            fps: "24.00",
            failure_reason: None,
        },
        Job {
            input: "podcast_cam.mp4",
            output: "podcast_cam.mp4",
            preset: "archive h265",
            stage: "writing output",
            duration: "00:27:12",
            input_size_mb: 3_420,
            target_output_mb: 1_860,
            target_bitrate_kbps: 9200,
            video_codec: "h264 -> h265",
            audio_codec: "aac stereo",
            resolution: "3840x2160",
            fps: "29.97",
            failure_reason: None,
        },
    ]
}
